'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Goals_Print

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LblEligible_Full_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEligible_Full_Review As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogin_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWindowBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWindowBatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataBaseBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataBaseBatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEmpl_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEmpl_Type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEMP_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMP_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divGoalText1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGoalText1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divOldTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOldTitle1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewTitle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewTitle1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewKey1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewKey1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewtarget1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewtarget1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''FUT_Goal_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit20 As Global.System.Web.UI.WebControls.Label
End Class
