'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Guild_FutureGoal

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''LblEligible_Full_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEligible_Full_Review As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogin_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGUILD_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGUILD_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLOYEE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLOYEE_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMgr_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMgr_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFirst_Mgr_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFirst_Mgr_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLOYEE_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLOYEE_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGR_UP_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGR_UP_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblSec_Mgr_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSec_Mgr_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLOYEE_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLOYEE_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGENERALIST_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGENERALIST_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblHR_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHR_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLOYEE_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLOYEE_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ReviseComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReviseComments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Future_Tasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Future_Tasks As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BtnFuture_Task control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFuture_Task As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del9 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del10 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel11 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del11 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel12 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del12 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel13 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del13 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask13 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel14 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del14 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask14 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel15 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del15 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask15 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel16 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del16 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask16 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel17 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del17 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask17 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del18 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask18 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel19 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del19 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask19 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel20 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_Del20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_Del20 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Fut_KeyTask20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask20 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Future_Tasks_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Future_Tasks_Review As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review11 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review12 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review13 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review14 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review15 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review16 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review17 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review18 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review19 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Tasks_Review20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Tasks_Review20 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Fut_KeyTask_Review20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Fut_KeyTask_Review20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Setting_Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Edit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BtnFuture_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFuture_Goal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal6 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal7 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal8 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal9 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_FutureGoal_Edit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Edit10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Delete_FutureGoal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete_FutureGoal10 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FUT_Goal_Edit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Succ_Edit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FUT_Date_Edit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Goal_Setting_Edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Edit1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BtnSubmit_UpperMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSubmit_UpperMgr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Goal_Setting_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Review As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Discussion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Discussion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Disc_Com control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disc_Com As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DiscussionComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscussionComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Discuss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Discuss As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Generalist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Generalist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Approve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Approve As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Sub_Empl_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sub_Empl_Review As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goals_Log control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goals_Log As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Sub_Empl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sub_Empl As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Empl_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Empl_Review As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton
End Class
