'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FutureGoals_Print

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LblEligible_Full_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEligible_Full_Review As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogin_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFirst_SUP_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirst_SUP_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMAIL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMAIL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFlag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEMP_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMP_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblUP_MGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUP_MGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblHR_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHR_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ReviseComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReviseComments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''divNewtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewtext As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Goal_Setting_Edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Edit As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''divGoalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGoalText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divOldTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOldTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewKey As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewtarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewtarget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGoal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblGoal10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoal10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSuccess10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuccess10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDate10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDate10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Setting_Edit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Edit1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''BtnSubmit_UpperMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSubmit_UpperMgr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Goal_Setting_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Setting_Review As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review6 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review7 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review8 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review9 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_FutureGoal_Review10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_FutureGoal_Review10 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FUT_Goal_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Goal_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Succ_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Succ_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUT_Date_Edit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUT_Date_Edit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Discussion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Discussion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Disc_Com control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disc_Com As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DiscussionComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscussionComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Discuss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Discuss As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Generalist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Generalist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Approve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Approve As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Sub_Empl_Review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sub_Empl_Review As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goals_Log control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goals_Log As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
