'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Appraisal11

    '''<summary>
    '''form2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFIRST_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFIRST_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSECOND_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSECOND_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYEAR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FY_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FY_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEMP_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMP_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''COLL_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COLL_MGT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCOLL_MGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCOLL_MGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblUP_MGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUP_MGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblHR_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHR_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAccomplishment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccomplishment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbMake_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMake_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMake_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblStrengths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStrengths As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDevelopment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDevelopment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbBelow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBelow1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbNeed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNeed1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMeet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMeet1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbExceed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbExceed1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbDisting1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDisting1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblOverall_Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverall_Summary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_ResetAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_ResetAppraisal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ResetAppraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetAppraisal As Global.System.Web.UI.WebControls.Button
End Class
