'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Guild_Appraisal1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFIRST_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFIRST_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSECOND_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSECOND_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYEAR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FY_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FY_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEMP_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMP_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCOLL_MGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCOLL_MGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblUP_MGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUP_MGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblHR_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHR_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbAccomp1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbAccomp1A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbStrengthsA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbStrengthsA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDevelopment_AreasA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDevelopment_AreasA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbBelow1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBelow1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbNeed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNeed1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMeet1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMeet1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbExceed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbExceed1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbDisting1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDisting1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txbOverall_SumA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbOverall_SumA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Development_Plan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Development_Plan1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbDevelopment_ObjectiveA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDevelopment_ObjectiveA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbMake_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMake_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbMake_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbBuild2_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLearn_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead2_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbProm_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbConf_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLead_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInsp_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbLeve_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Need As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Prof As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbComm_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Exce As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Smart_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Smart_Goal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Goal_Year3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Goal_Year5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goal_Year5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divNewtext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewtext As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divGoalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGoalText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divOldTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divOldTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewKey As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divNewtarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divNewtarget As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txbGoal1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal1A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess1A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate1A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal2_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal2_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal2A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess2A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate2A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate2A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal3_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal3_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal3A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess3A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate3A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate3A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal4_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal4_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal4A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess4A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate4A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate4A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal5_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal5_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal5A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess5A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate5A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate5A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal6_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal6_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal6A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess6A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate6A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate6A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal7_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal7_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal7A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal7A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess7A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess7A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate7A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate7A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal8_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal8_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal8A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal8A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess8A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess8A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate8A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate8A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal9_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal9_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal9A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal9A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess9A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess9A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate9A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate9A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Goal10_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal10_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txbGoal10A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbGoal10A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbSuccess10A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbSuccess10A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txbDate10A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDate10A As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmployeeComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmployeeComments As Global.System.Web.UI.WebControls.Label
End Class
