'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AppraisalHR_Review

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''Timer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Timer1 As Global.System.Web.UI.Timer

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLogin_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogin_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFIRST_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFIRST_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSECOND_MGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSECOND_MGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_Token control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_Token As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYEAR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_Email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGT_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGT_Email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUP_MGT_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUP_MGT_Email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_Email As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProcess_Flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProcess_Flag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWindowBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWindowBatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDataBaseBatch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataBaseBatch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMessage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SaveRecords1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SaveRecords1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FY_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FY_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblEMP_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMP_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_TITLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_TITLE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_DEPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_DEPT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''COLL_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COLL_MGT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCOLL_MGT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCOLL_MGT_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblUP_MGT_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUP_MGT_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmpl_HIRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpl_HIRE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHR_NAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblHR_Appr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHR_Appr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_Guld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Guld As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel_AllData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_AllData As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblAccomplishment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccomplishment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Accomplishment_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Accomplishment_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''RdbtYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbtYes As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RdbtNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbtNo As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txbAccomplishment_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbAccomplishment_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''trMake_Balanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMake_Balanced As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdMake_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMake_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Make_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Make_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbMake_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdMake_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMake_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Make_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Make_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbMake_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdMake_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMake_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Make_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Make_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbMake_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMake_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trBuild_Trust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBuild_Trust As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdBuild2_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBuild2_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Build_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Build_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbBuild2_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdBuild2_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBuild2_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Build_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Build_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbBuild2_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdBuild2_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBuild2_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Build_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Build_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbBuild2_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBuild2_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trLearn_Continuously control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLearn_Continuously As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdLearn_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLearn_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Learn_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Learn_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLearn_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLearn_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLearn_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Learn_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Learn_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLearn_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLearn_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLearn_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Learn_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Learn_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLearn_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLearn_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trLead_Urgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLead_Urgency As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdLead2_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead2_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead2_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead2_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead2_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLead2_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead2_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead2_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead2_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead2_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLead2_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead2_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead2_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead2_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead2_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead2_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trPromote_Collaboration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPromote_Collaboration As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdProm_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdProm_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Prom_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Prom_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbProm_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdProm_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdProm_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Prom_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Prom_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbProm_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdProm_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdProm_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Prom_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Prom_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbProm_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProm_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trConfront_Challenges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trConfront_Challenges As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdConf_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdConf_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Conf_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Conf_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbConf_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdConf_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdConf_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Conf_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Conf_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbConf_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdConf_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdConf_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Conf_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Conf_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbConf_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbConf_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trLead_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLead_Change As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdLead_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLead_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLead_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLead_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Lead_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Lead_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLead_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLead_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trInspire_Risk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInspire_Risk As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdInsp_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdInsp_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Insp_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Insp_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbInsp_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdInsp_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdInsp_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Insp_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Insp_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbInsp_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdInsp_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdInsp_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Insp_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Insp_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbInsp_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInsp_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trLeverage_External control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trLeverage_External As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdLeve_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLeve_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Leve_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Leve_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLeve_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLeve_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLeve_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Leve_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Leve_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLeve_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdLeve_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdLeve_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Leve_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Leve_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbLeve_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLeve_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''trCommunicate_Impact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCommunicate_Impact As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdComm_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdComm_Need1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Comm_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Comm_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbComm_Need1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Need1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdComm_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdComm_Prof1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Comm_Prof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Comm_Prof As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbComm_Prof1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Prof1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdComm_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdComm_Exce1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Comm_Exce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Comm_Exce As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbComm_Exce1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbComm_Exce1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UpdatePanel_Competencies_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Competencies_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txbCompetencies_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbCompetencies_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView6 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblStrengths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStrengths As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Strengths_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Strengths_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txbStrengths_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbStrengths_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblDevelopment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDevelopment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Development_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Development_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txbDevelopment_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbDevelopment_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView3 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource3 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''trOverall_Performance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trOverall_Performance As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''tdBelow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdBelow As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Rating_Below control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Rating_Below As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbBelow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBelow As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdNeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNeed As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Rating_Need control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Rating_Need As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbNeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNeed As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdMeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdMeet As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Rating_Meet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Rating_Meet As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbMeet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMeet As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdExceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdExceed As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Rating_Exceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Rating_Exceed As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbExceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbExceed As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tdDisting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdDisting As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''UpdatePanel_Rating_Disting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Rating_Disting As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbDisting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDisting As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''UpdatePanel_Overall_Performance_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Overall_Performance_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txbOverall_Performance_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbOverall_Performance_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView4 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource4 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblOverall_Summary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverall_Summary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel_Overall_Summary_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel_Overall_Summary_Comm As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txbOverall_Summary_Comm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txbOverall_Summary_Comm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GridView5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView5 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlDataSource5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource5 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnDiscuss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDiscuss As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApproved As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Img_Print1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img_Print1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
