'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Default_Print

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblDEPTID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDEPTID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblYEAR_PRINT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYEAR_PRINT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Ln control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Generalist_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Generalist_Name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Generalist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Generalist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Manager_Name_GLD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Manager_Name_GLD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Manager_GLD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Manager_GLD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Department_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Department_Name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Department As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln20 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents All As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Report As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Panel_Goals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goals As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Goals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Goals As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Goals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Goals As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln9 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Panel_MidPoint_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_MidPoint_Print As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Mid_Point control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mid_Point As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_MidPoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_MidPoint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln10 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln11 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln12 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Generalist_Name_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Generalist_Name_MGT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Generalist_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Generalist_MGT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln13 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln14 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Manager_Name_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Manager_Name_MGT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Manager_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Manager_MGT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln15 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln16 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Department_Name_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Department_Name_MGT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Department_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Department_MGT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln17 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Ln18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln18 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''All_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents All_MGT As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Report_MGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Report_MGT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Ln19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ln19 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Panel_Terminated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Terminated As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Terminated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Terminated As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Report_TER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Report_TER As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Individual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Individual As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Report_IND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Report_IND As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
