'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Default_HR

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblEMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMGT_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMGT_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMyEmployee_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyEmployee_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMyEmployee_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMyEmployee_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWaiting_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaiting_Year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWaiting_EMPLID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaiting_EMPLID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNAME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Panel_My_Appraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_My_Appraisal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_MY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_MY As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitPer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_My_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_My_Goal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_My_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_My_Goal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Goal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Goal1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_My_Staff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_My_Staff As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel_My_Employees_Appraisal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_My_Employees_Appraisal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_Employees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Employees As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLMy_Employees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLMy_Employees As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitMyEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitMyEmployees As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Employee_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Employee_Goal As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Year_MyEmpl_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Year_MyEmpl_Goal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLMyEmpl_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLMyEmpl_Goal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_MyEmpl_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_MyEmpl_Goal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_My_Staff1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_My_Staff1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Panel_Appraisal_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Appraisal_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Waiting As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEmployees_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEmployees_Waiting As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitWaiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitWaiting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Goal_Waiting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goal_Waiting As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Goal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEmployees_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEmployees_Goal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Goal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Goal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Appraisal_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Appraisal_Report As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Report As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEmployees_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEmployees_Report As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Goals_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Goals_Report As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYearsGoals_Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYearsGoals_Reports As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLGoals_Reports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLGoals_Reports As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_Goals_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_Goals_Report As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Midpoint_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Midpoint_Report As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYear_MidPoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYear_MidPoint As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLEmployees_Midpoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLEmployees_Midpoint As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit_MidPoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit_MidPoint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Employee_Adjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Employee_Adjustment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYear_Change_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYear_Change_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDL_Change_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Change_Department As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitDepartment_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitDepartment_Change As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Appraisal_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Appraisal_Print As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDLYears_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Print As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLBulk_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLBulk_Print As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BulkPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BulkPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Appraisal_Term_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Appraisal_Term_Print As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DDEmployees_Term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDEmployees_Term As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DDLYears_Term_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDLYears_Term_Print As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BulkPrint_Term control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BulkPrint_Term As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton
End Class
